[package]
name = "processControl"
version = "0.1.0"
authors = ["御承扬 <2923616405@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
